# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f75ba5f0aa5db3f983a891556a3be7ca710cad3a0f3fb8ec81649e08e04f3919ba7331bb39b2c617baf9a7a6b46d5d6e9195f87626f13c60e10752f52e0b611

test:
  secret_key_base: 87793996b553603cc72f0a366ff2e979bb6aa9df891de91b6313246910f36408bfe8f7d45375151b33dfbb2292053d509fe93539a594df4f2b63f0a597c4c28d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
